version: '3.7'

services:
  gitea:
    image: gitea/gitea:1.12.3
    environment:
      - USER_UID=1000
      - USER_GID=1000
    volumes:
      - ./etc/gitea:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=https"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${KITT_DOMAIN}`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
      - "traefik.tcp.routers.ssh.entrypoints=ssh"
      - "traefik.tcp.routers.ssh.rule=HostSNI(`*`)"
      - "traefik.tcp.services.ssh.loadbalancer.server.port=22"

networks:
  default:
    external:
      name: kitt
