version: '3.7'

services:
  drone:
    image: drone/drone:1
    volumes:
      - "./data/drone:/data"
    ports:
      - 80
    env_file: .env
    environment:
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST=drone.whoa.bot
      - DRONE_SERVER_PROTO=https
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
  drone-runner:
    image: drone/drone-runner-docker:1
    env_file: .env
    environment:
      - DRONE_RPC_SECRET
      - DRONE_RPC_HOST=drone.whoa.bot
      - DRONE_RPC_PROTO=https
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=runner
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
