version: '3.7'

services:
  drone:
    image: drone/drone:1
    volumes:
      - "./data/drone:/data"
    env_file: .env
    environment:
      - DRONE_RPC_SECRET
      - DRONE_SERVER_HOST=drone.defn.sh
      - DRONE_SERVER_PROTO=https
      - DRONE_GITHUB_CLIENT_ID
      - DRONE_GITHUB_CLIENT_SECRET
      - DRONE_USER_CREATE
      - DRONE_USER_FILTER
      - DRONE_REGISTRATION_CLOSED=true
      - DRONE_LIMIT_EVENTS=push,tag
    labels:
      - "hera.hostname=drone.defn.sh"
      - "hera.port=80"
    links:
      - drone-vault
  drone-runner:
    image: drone/drone-runner-docker:1
    env_file: .env
    environment:
      - DRONE_RPC_SECRET
      - DRONE_RPC_HOST=drone
      - DRONE_RPC_PROTO=http
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=runner
      - DRONE_SECRET_PLUGIN_ENDPOINT=http://drone-vault:3000
      - DRONE_SECRET_PLUGIN_TOKEN
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    links:
      - drone
      - drone-vault
  drone-vault:
    image: drone/vault
    environment:
      - DRONE_DEBUG=true
      - DRONE_SECRET
      - VAULT_ADDR=https://vault.whoa.bot
      - VAULT_TOKEN
