version: '3.7'
services:
  drone:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`drone.whoa.bot`,`drone.defn.sh`) && PathPrefix(`/hook`)"

networks:
  default:
    external:
      name: kitt
