version: '3.7'

services:
  drone:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drone.rule=Host(`drone.defn.sh`,`drone.whoa.bot`)"

networks:
  default:
    external:
      name: kitt
