#!/bin/bash

# USAGE: kiki [flags] pipeline
#
# Run a drone pipeline

function options {
  true
}

function main {
  for _p in "$@"; do 
    echo "INFO: running pipeline $_p"
    drone exec --pipeline "$_p"
  done
}

source sub "$0" "$@"
